#######################################
#
# インフラで利用する環境変数のtemplate
#
#######################################
#######################################
# settings
#######################################
AWS_REGION: ap-northeast-1
AWS_CLI_PROFILE: '' # ← !!! 自分の開発環境のAWS CLIのProfile名を入力しよう
#######################################
# cloud front
#######################################
CLOUDFRONT_DYNAMIC_CACHE_POLICY_NAME: chillnn-training-front-dynamic-cache-policy-${self:provider.stage}
CLOUDFRONT_STATIC_CACHE_POLICY_NAME: chillnn-training-front-static-cache-policy-${self:provider.stage}
CLOUDFRONT_ALIASES:
    - '' # ← !!! 自分でドメインを取る必要がある
CLOUDFRONT_ALIAS_ACM_ARN: '' # ← !!! 自分でACMから証明書を発行する必要がある
#######################################
# s3
#######################################
S3_BUCKET_NAME: '' # ← !!! バケット名は世界でユニークである必要がある。自分で名前をつけてみましょう
# ex) S3_BUCKET_NAME: 'chillnn-training-front-nuxt-${self:provider.stage}' <- suffixとして、${-stage名}をつけるようにしてください。
